name: gentry_pharmaceuticals_app
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  shared_preferences: ^2.0.17
  lazy_load_scrollview: 1.3.0
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  multiselect: ^0.1.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/